/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektpo;

import baza.*;
import java.text.ParseException;
import java.util.List;
import javax.swing.text.MaskFormatter;


/**
 *Klasa dla jednego z paneli wyświetlanych w klasie Gui
 * @author Michał Rembisz
 */
public class DodajPanel extends javax.swing.JPanel {

    /**
     * Creates new form DodajPanel
     */
    public DodajPanel() {
        initComponents();
    }
    
    /**
     * Metoda sprawdza czy podany napis zawiera tylko cyfry i ma 9 znaków
     * @param tel zmienna typu String zawierająca napis do sprawdzenia
     * @return metoda zwraca wartość logiczną true lub false informującą czy podany napis zawiera tylko cyfry
     */
    public  boolean checkTelefon(String tel){
         
        boolean SameLiczby=true;
        int i=0;
        while(SameLiczby==true && i<tel.length()){
            if(tel.charAt(i)<='0'|| tel.charAt(i)>='9'||tel.length()!=9){
                SameLiczby=false; 
            }
            ++i;
        } 
        return SameLiczby;
    }
    /**
     * Metoda sprawdza czy podany napis zawiera tylko cyfry
     * @param liczba zmienna typu String zawierająca napis do sprawdzenia
     * @return metoda zwraca wartość logiczną true lub false informującą czy podany napis zawiera tylko cyfry
     */
    public boolean checkLiczby (String liczba){
        boolean SameLiczby=true;
        int i=0;
        while(SameLiczby==true && i<liczba.length()){
            if(liczba.charAt(i)<='0'|| liczba.charAt(i)>='9'){
                SameLiczby=false; 
            }
            ++i;
        } 
        return SameLiczby;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        podajImie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        podajNazwisko = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        podajRejon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        podajZmiane = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pracoId_aCombo = new javax.swing.JComboBox<>();
        dodajpButton = new javax.swing.JButton();
        powiadoLabelp = new javax.swing.JLabel();
        podajTel_p = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        podajMiejscowosc = new javax.swing.JTextField();
        podajUlice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        podajnr_domu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        podajPoczte = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dodajaButton = new javax.swing.JButton();
        try
        {
            MaskFormatter kodpocztowy = new MaskFormatter("##-###");
            kodpocztowy.setValidCharacters("0123456789");
            kodField = new javax.swing.JFormattedTextField(kodpocztowy);
            powiadoLabela = new javax.swing.JLabel();
            jPanel3 = new javax.swing.JPanel();
            jLabel12 = new javax.swing.JLabel();
            podajImieK = new javax.swing.JTextField();
            jLabel13 = new javax.swing.JLabel();
            podajNazwiskoK = new javax.swing.JTextField();
            jLabel14 = new javax.swing.JLabel();
            podajTelefonK = new javax.swing.JTextField();
            jLabel15 = new javax.swing.JLabel();
            adresComboK = new javax.swing.JComboBox<>();
            dodajkButton = new javax.swing.JButton();
            powiadoLabelk = new javax.swing.JLabel();
            jPanel4 = new javax.swing.JPanel();
            jLabel16 = new javax.swing.JLabel();
            typ_zlCombo = new javax.swing.JComboBox<>();
            jLabel17 = new javax.swing.JLabel();
            adresComboz = new javax.swing.JComboBox<>();
            jLabel18 = new javax.swing.JLabel();
            pracownikCombo = new javax.swing.JComboBox<>();
            jLabel19 = new javax.swing.JLabel();
            klientCombo = new javax.swing.JComboBox<>();
            jButton1 = new javax.swing.JButton();
            powiadoLabelz = new javax.swing.JLabel();

            jLabel2.setText("Imie:");

            jLabel3.setText("Nazwisko:");

            jLabel4.setText("Rejon");

            jLabel5.setText("Zmiana");

            jLabel6.setText("Telefon:");

            jLabel7.setText("Adres:");

            dodajpButton.setText("Dodaj");
            dodajpButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    dodajpButtonActionPerformed(evt);
                }
            });

            powiadoLabelp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(powiadoLabelp, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(podajTel_p, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(podajZmiane, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(podajRejon, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(podajNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(podajImie, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(pracoId_aCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addComponent(dodajpButton)))
                    .addContainerGap(65, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(podajImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(podajNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(podajRejon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(podajZmiane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(podajTel_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(pracoId_aCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(powiadoLabelp)
                    .addGap(50, 50, 50)
                    .addComponent(dodajpButton)
                    .addContainerGap(66, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Pracownicy", jPanel1);

            jLabel1.setText("Miejscowość:");

            jLabel8.setText("Ulica:");

            jLabel9.setText("Nr domu/mieszkania:");

            jLabel10.setText("Kod:");

            jLabel11.setText("Poczta:");

            dodajaButton.setText("Dodaj");
            dodajaButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    dodajaButtonActionPerformed(evt);
                }
            });

        }
        catch (ParseException e) {
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(podajUlice, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(podajMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kodField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(podajnr_domu, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(podajPoczte, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(powiadoLabela)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(dodajaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(podajMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(podajUlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(podajnr_domu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(podajPoczte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(powiadoLabela)
                .addGap(59, 59, 59)
                .addComponent(dodajaButton)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adresy", jPanel2);

        jLabel12.setText("Imie:");

        jLabel13.setText("Nazwisko:");

        jLabel14.setText("Telefon:");

        jLabel15.setText("Adres:");

        dodajkButton.setText("Dodaj");
        dodajkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(podajTelefonK)
                            .addComponent(adresComboK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(powiadoLabelk)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(podajNazwiskoK)
                            .addComponent(podajImieK))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(dodajkButton)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(podajImieK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(podajNazwiskoK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(podajTelefonK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(adresComboK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(powiadoLabelk)
                .addGap(27, 27, 27)
                .addComponent(dodajkButton)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Klienci", jPanel3);

        jLabel16.setText("Typ zlecenia:");

        typ_zlCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Naprawa", "Instalacja", "Deinstalacja", "Wycena" }));

        jLabel17.setText("Adres:");

        jLabel18.setText("Pracownik:");

        jLabel19.setText("Klient:");

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton1)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(powiadoLabelz)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(klientCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pracownikCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typ_zlCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adresComboz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(typ_zlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresComboz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pracownikCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(klientCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(powiadoLabelz)
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Zlecenia", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda obsługi zdarzenia dla dodajpButton - pobiera wartości zmiennych z pól tekstowych, sprawdza czy wszystkie pola są prawidłowo wypełnione
     * oraz dodaj rekord do bazy danych do tabeli pracownicy i dodaje wiersz do obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void dodajpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajpButtonActionPerformed
        
        List<Pracownik> pracownicy = Gui.b.selectPracownicy();
        
        
        boolean dodaj=true;
        String tel_p="0";
        if(checkTelefon(podajTel_p.getText())==true){
            tel_p=podajTel_p.getText();
            
        }else{
            dodaj=false;
            powiadoLabelp.setText("Nie poprawny numer telefonu");   
        }
                      
        String imie =podajImie.getText();
        String nazwisko=podajNazwisko.getText();
        String rejon=podajRejon.getText();        
        String zmiana=podajZmiane.getText(); 
        
        if(podajImie.getText().equals("")||podajNazwisko.getText().equals("")||podajRejon.getText().equals("")||podajZmiane.getText().equals("")||
                                    podajTel_p.getText().equals("")||pracoId_aCombo.getSelectedItem().equals("")){
            powiadoLabelp.setText("Nie wprowadzono wszystkich danych");
        }
        Object id_a=pracoId_aCombo.getSelectedItem();
        {
            for(int i=0;i<pracownicy.size();i++){
                if(pracownicy.get(i).getTel_p().equals(tel_p)){
                    
                    powiadoLabelp.setText("Pracownik o podanym numerze telefonu już znajduję się w bazie");   
                    dodaj=false;
                }
            }
        }
        if(dodaj==true){
            
            pracownicy.clear();
            
            Gui.b.insertPracownik(imie, nazwisko, rejon, zmiana, tel_p, id_a.toString());
            pracownicy.clear();
            pracownicy=Gui.b.selectPracownicy();
            int ostatni=pracownicy.size()-1;
            String id_p=pracownicy.get(ostatni).getId_p();
             Gui.wyswietlFrame.addNewRowsPracownicy(id_p,imie,nazwisko,rejon,zmiana,tel_p,id_a.toString());
             powiadoLabelp.setText("");
             pracownicy.clear();
      
        }
    }//GEN-LAST:event_dodajpButtonActionPerformed
    /**
     * Metoda obsługi zdarzenia dla dodajaButton - pobiera wartości zmiennych z pól tekstowych, sprawdza czy wszystkie pola są prawidłowo wypełnione
     * oraz dodaj rekord do bazy danych do tabeli adresy i dodaje wiersz do obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void dodajaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajaButtonActionPerformed
        List<Adres> adresy = Gui.b.selectAdresy();
        boolean dodaj=true;
        String miejscowosc =podajMiejscowosc.getText();
        String ulica=podajUlice.getText();
        String nr_domu=podajnr_domu.getText();        
        String kod=kodField.getText(); 
        String poczta=podajPoczte.getText(); 
        
        if(podajMiejscowosc.getText().equals("")||podajUlice.getText().equals("")||podajnr_domu.getText().equals("")||kodField.getText().equals("  -   ")||
                                    podajPoczte.getText().equals("")){
            powiadoLabela.setText("Nie wprowadzono wszystkich danych");
            dodaj=false;
        }
        
         if(dodaj==true){

            Gui.b.insertAdres(miejscowosc,ulica,nr_domu,kod,poczta);
            
            adresy=Gui.b.selectAdresy();
            int ostatni=adresy.size()-1;
            String id_a=adresy.get(ostatni).getId_a();
             Gui.wyswietlFrame.addNewRowsAdresy(id_a,miejscowosc,ulica,nr_domu,kod,poczta);
             powiadoLabela.setText("");
             adresy.clear();
         }
         
    }//GEN-LAST:event_dodajaButtonActionPerformed

    /**
     * Metoda obsługi zdarzenia dla dodajkButton - pobiera wartości zmiennych z pól tekstowych, sprawdza czy wszystkie pola są prawidłowo wypełnione
     * oraz dodaj rekord do bazy danych do tabeli klienci i dodaje wiersz do obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void dodajkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajkButtonActionPerformed
       List<Klient> klienci = Gui.b.selectKlienci();
        boolean dodaj=true;
        String tel_k="0";
        if(checkTelefon(podajTelefonK.getText())==true){
            tel_k=podajTelefonK.getText();
            
        }else{
            dodaj=false;
            powiadoLabelk.setText("Nie poprawny numer telefonu");   
        }
        
        String imie =podajImieK.getText();
        String nazwisko=podajNazwiskoK.getText();
        
        
        if(podajImieK.getText().equals("")||podajNazwiskoK.getText().equals("")||
                                    podajTelefonK.getText().equals("")||adresComboK.getSelectedItem().equals("")){
            powiadoLabelp.setText("Nie wprowadzono wszystkich danych");
        }
        Object id_a=adresComboK.getSelectedItem();
        {
            for(int i=0;i<klienci.size();i++){
                if(klienci.get(i).getTel_k().equals(tel_k)){
                    
                    powiadoLabelp.setText("Klient o podanym numerze telefonu już znajduję się w bazie");   
                    dodaj=false;
                }
            }
        }
        
         if(dodaj==true){
            
            klienci.clear();
            
            Gui.b.insertKlient(imie, nazwisko, tel_k, id_a.toString());
            klienci.clear();
            klienci=Gui.b.selectKlienci();
            int ostatni=klienci.size()-1;
            String id_k=klienci.get(ostatni).getId_k();
             Gui.wyswietlFrame.addNewRowsKlienci(id_k,imie,nazwisko,tel_k,id_a.toString());
             powiadoLabelp.setText("");
             klienci.clear();
      
        }
      
    }//GEN-LAST:event_dodajkButtonActionPerformed

    /**
     * Metoda obsługi zdarzenia dla jButton1 - pobiera wartości zmiennych z pól tekstowych, sprawdza czy wszystkie pola są prawidłowo wypełnione
     * oraz dodaj rekord do bazy danych do tabeli zlecenia i dodaje wiersz do obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Adres> adresy = Gui.b.selectAdresy();
        List<Pracownik> pracownicy = Gui.b.selectPracownicy();
        List<Klient> klienci = Gui.b.selectKlienci();
        boolean dodaj=true;
        
        Object typ_zl=typ_zlCombo.getSelectedItem();
        Object id_a=adresComboz.getSelectedItem();
        Object id_p=pracownikCombo.getSelectedItem();
        Object id_k=klientCombo.getSelectedItem();
        
        Gui.b.insertZlecenie(typ_zl.toString(),id_a.toString(), id_p.toString(), id_k.toString());
        
        if(dodaj==true){
        
        adresy.clear();
        pracownicy.clear();
        klienci.clear();
        
        adresy = Gui.b.selectAdresy();
        pracownicy = Gui.b.selectPracownicy();
        klienci = Gui.b.selectKlienci();
        
        List<Zlecenie> zlecenia = Gui.b.selectZlecenia();
        
        int ostatni=zlecenia.size()-1;
            String id_z=zlecenia.get(ostatni).getId_z();
             Gui.wyswietlFrame.addNewRowsZlecenia(id_z,typ_zl.toString(),id_a.toString(), id_p.toString(), id_k.toString());
             powiadoLabelz.setText("");
        
        }
        adresy.clear();
        pracownicy.clear();
        klienci.clear();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> adresComboK;
    public javax.swing.JComboBox<String> adresComboz;
    private javax.swing.JButton dodajaButton;
    private javax.swing.JButton dodajkButton;
    private javax.swing.JButton dodajpButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JComboBox<String> klientCombo;
    private javax.swing.JFormattedTextField kodField;
    private javax.swing.JTextField podajImie;
    private javax.swing.JTextField podajImieK;
    private javax.swing.JTextField podajMiejscowosc;
    private javax.swing.JTextField podajNazwisko;
    private javax.swing.JTextField podajNazwiskoK;
    private javax.swing.JTextField podajPoczte;
    private javax.swing.JTextField podajRejon;
    private javax.swing.JTextField podajTel_p;
    private javax.swing.JTextField podajTelefonK;
    private javax.swing.JTextField podajUlice;
    private javax.swing.JTextField podajZmiane;
    private javax.swing.JTextField podajnr_domu;
    private javax.swing.JLabel powiadoLabela;
    private javax.swing.JLabel powiadoLabelk;
    private javax.swing.JLabel powiadoLabelp;
    private javax.swing.JLabel powiadoLabelz;
    public javax.swing.JComboBox<String> pracoId_aCombo;
    public javax.swing.JComboBox<String> pracownikCombo;
    private javax.swing.JComboBox<String> typ_zlCombo;
    // End of variables declaration//GEN-END:variables
}
