/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektpo;

import baza.Obsbazy;
import java.util.List;
import baza.*;

/**
 *Główna klasa projektu zawiera interfejs użytkownika
 * @author Michał Rembisz
 */
public class Gui extends javax.swing.JFrame {

     public static Obsbazy b;
    private boolean polaczenie=false;
    public static String wynik= "";
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wyswietlFrame = new projektpo.WyswietlFrame();
        MainPanel = new javax.swing.JPanel();
        RightPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel11 = new projektpo.Panel1();
        dodajPanel = new projektpo.DodajPanel();
        parsujPanel = new projektpo.ParsujPanel();
        usuwaniePanel = new projektpo.UsuwaniePanel();
        updatePanel = new projektpo.UpdatePanel();
        LeftPanel = new javax.swing.JPanel();
        PolaczButton = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        dodajdobazyButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        czyscbazeButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(405, 400));

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));

        RightPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        RightPanel.add(jPanel1, "card7");
        RightPanel.add(panel11, "card5");
        RightPanel.add(dodajPanel, "card3");
        RightPanel.add(parsujPanel, "card2");
        RightPanel.add(usuwaniePanel, "card4");
        RightPanel.add(updatePanel, "card6");

        PolaczButton.setText("Połącz");
        PolaczButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolaczButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Pobierz z XML");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dodajdobazyButton.setEnabled(false);
        dodajdobazyButton.setText("Dodaj do bazy");
        dodajdobazyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajdobazyButtonActionPerformed(evt);
            }
        });

        jButton2.setEnabled(false);
        jButton2.setText("Wyświetl baze");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        czyscbazeButton.setEnabled(false);
        czyscbazeButton.setText("Usuń z bazy");
        czyscbazeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czyscbazeButtonActionPerformed(evt);
            }
        });

        jButton3.setEnabled(false);
        jButton3.setText("Wykonaj inne zapytanie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setEnabled(false);
        jButton4.setText("Aktualizuj rekord");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PolaczButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dodajdobazyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(czyscbazeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(dodajdobazyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(czyscbazeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(51, 51, 51)
                .addComponent(jButton2)
                .addGap(53, 53, 53)
                .addComponent(PolaczButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Plik");

        jMenuItem4.setText("Wyjdź");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edytuj");

        jMenuItem2.setText("Pobierz z XML");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Baza danych");

        jMenuItem1.setText("Polacz");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        jMenuItem1.getAccessibleContext().setAccessibleName("jMenuItem1");
        jMenuItem1.getAccessibleContext().setAccessibleDescription("");

        jMenuItem3.setEnabled(false);
        jMenuItem3.setText("Dodaj");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem5.setEnabled(false);
        jMenuItem5.setText("Aktualizuj");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setEnabled(false);
        jMenuItem6.setText("Usuń");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setEnabled(false);
        jMenuItem7.setText("Inne zapytanie");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setEnabled(false);
        jMenuItem8.setText("Wyświet");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda obsługi zdarzenia dla jMenuItem4 - zamyka program
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla jButton1 - zmienia panel widziany w RightPanel na parsujPanel
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(parsujPanel);
        RightPanel.repaint();
        RightPanel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla PolaczButton - łączy/rozłącza z bazą włącza przyciski
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void PolaczButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolaczButtonActionPerformed
        if(polaczenie==false){
            b = new Obsbazy();

            polaczenie=true;
            System.out.println("Połączono");
            PolaczButton.setSelected(polaczenie);
            PolaczButton.setText("Rozłacz");
            jMenuItem1.setText("Rozłacz");
            jMenuItem3.setEnabled(true);
            jMenuItem7.setEnabled(true);
            jMenuItem5.setEnabled(true);
            jMenuItem6.setEnabled(true);
            jMenuItem8.setEnabled(true);
            dodajdobazyButton.setEnabled(true);
            czyscbazeButton.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            
            wyswietlFrame.clearAdresy();
        wyswietlFrame.clearKlienci();
        wyswietlFrame.clearPracownicy();
        wyswietlFrame.clearZlecenia();
        
       
        
        List<Pracownik> pracownicy = b.selectPracownicy();
        for(int i=0; i<pracownicy.size(); i++)
        {
            wyswietlFrame.addNewRowsPracownicy(pracownicy.get(i).getId_p(), pracownicy.get(i).getImie(), pracownicy.get(i).getNazwisko(), pracownicy.get(i).getRejon(), pracownicy.get(i).getZmiana(), pracownicy.get(i).getTel_p(), pracownicy.get(i).getId_a());
        }
        
        List<Adres> adresy = b.selectAdresy();
        for(int i=0; i<adresy.size(); i++)
        {
            wyswietlFrame.addNewRowsAdresy(adresy.get(i).getId_a(), adresy.get(i).getMiejscowosc(), adresy.get(i).getUlica(), adresy.get(i).getNr_domu(), adresy.get(i).getKod(), adresy.get(i).getPoczta());
        }
        
        List<Klient> klienci = b.selectKlienci();
        for(int i=0; i<klienci.size(); i++)
        {
            wyswietlFrame.addNewRowsKlienci(klienci.get(i).getId_k(), klienci.get(i).getImie(), klienci.get(i).getNazwisko(), klienci.get(i).getTel_k(), klienci.get(i).getId_a());
        }
        
        List<Zlecenie> zlecenia = b.selectZlecenia();
        for(int i=0; i<zlecenia.size(); i++)
        {
            wyswietlFrame.addNewRowsZlecenia(zlecenia.get(i).getId_z(), zlecenia.get(i).getTyp_zl(), zlecenia.get(i).getId_a(), zlecenia.get(i).getId_p(), zlecenia.get(i).getId_k());
        }
        
        pracownicy.clear();
        adresy.clear();
        klienci.clear();
        zlecenia.clear();
        

        }
        else if(polaczenie==true){
            b.closeConnection();
            polaczenie=false;
            System.out.println("Rozłączono");

            PolaczButton.setSelected(polaczenie);
            PolaczButton.setText("Połącz");
            jMenuItem1.setText("Połącz");
            System.exit(0);
        }
    }//GEN-LAST:event_PolaczButtonActionPerformed
/**
 * Metoda zdarzenia dla przycisku dodajdobazyButton - tworzy listy na podstawie bazy danych dodaje elementy do jComboBoxów, zmienia panel na dodajPanel
 * @param evt pobiera informacje o wystąpieniu zdarzenia
 */
    private void dodajdobazyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajdobazyButtonActionPerformed
        List<Adres> adresy = b.selectAdresy();
        List<Pracownik> pracownicy = b.selectPracownicy();
        List<Klient> klienci = b.selectKlienci();
        for(int i=0; i<adresy.size(); i++){
            dodajPanel.pracoId_aCombo.addItem(adresy.get(i).getId_a());
            dodajPanel.adresComboK.addItem(adresy.get(i).getId_a());
            dodajPanel.adresComboz.addItem(adresy.get(i).getId_a());
            
            
        }
        for(int i=0; i<pracownicy.size(); i++)
            dodajPanel.pracownikCombo.addItem(pracownicy.get(i).getId_p());
        for(int i=0; i<klienci.size(); i++)
            dodajPanel.klientCombo.addItem(klienci.get(i).getId_k());
        
        adresy.clear();
        pracownicy.clear();
        klienci.clear();
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(dodajPanel);
        RightPanel.repaint();
        RightPanel.revalidate();
    }//GEN-LAST:event_dodajdobazyButtonActionPerformed
/**
     * Metoda obsługi zdarzenia dla jButton2 - wyświetla wyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        wyswietlFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla jMenuItem1 - wykonuje metode obsługi zdarzeń dla PolaczButton
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PolaczButtonActionPerformed(evt);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla czyscbazeButton - tworzy listy na podstawie bazy danych dodaje elementy do jComboBoxów, zmienia panel na usuwaniePanel
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void czyscbazeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czyscbazeButtonActionPerformed
        List<Adres> adresy = b.selectAdresy();
        List<Pracownik> pracownicy = b.selectPracownicy();
        List<Klient> klienci = b.selectKlienci();
        List<Zlecenie> zlecenia = b.selectZlecenia();
        
        for(int i=0; i<pracownicy.size(); i++){
            usuwaniePanel.utCombo.addItem(pracownicy.get(i).getTel_p());
            usuwaniePanel.uidpCombo.addItem(pracownicy.get(i).getId_p());
        }
        
        for(int i=0; i<adresy.size(); i++){
            usuwaniePanel.uidaCombo.addItem(adresy.get(i).getId_a());
            
        }
        
        for(int i=0; i<klienci.size(); i++){
            usuwaniePanel.utkCombo.addItem(klienci.get(i).getTel_k());
            usuwaniePanel.uidkCombo.addItem(klienci.get(i).getId_k());
        }
        
        for(int i=0; i<zlecenia.size(); i++){
            usuwaniePanel.uidzCombo.addItem(zlecenia.get(i).getId_z());
            
        }
        
        adresy.clear();
        pracownicy.clear();
        klienci.clear();
        zlecenia.clear();

        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(usuwaniePanel);
        RightPanel.repaint();
        RightPanel.revalidate();
    }//GEN-LAST:event_czyscbazeButtonActionPerformed

    /**
     * Metoda obsługi zdarzenia dla czyscbazeButton - zmienia panel na panel11
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(panel11);
        RightPanel.repaint();
        RightPanel.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla czyscbazeButton - tworzy listy na podstawie bazy danych dodaje elementy do jComboBoxów, zmienia panel na updatePanel
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       List<Adres> adresy = b.selectAdresy();
        List<Pracownik> pracownicy = b.selectPracownicy();
        List<Klient> klienci = b.selectKlienci();
        List<Zlecenie> zlecenia = b.selectZlecenia();
         
        for(int i=0; i<pracownicy.size(); i++)
        {updatePanel.uidpCombop.addItem(pracownicy.get(i).getId_p());
        updatePanel.pracownikCombo.addItem(pracownicy.get(i).getId_p());
        
        }
        for(int i=0; i<adresy.size(); i++){
            updatePanel.uidaCombop.addItem(adresy.get(i).getId_a());
            updatePanel.adresCombo.addItem(adresy.get(i).getId_a());
            updatePanel.adresComboK.addItem(adresy.get(i).getId_a());
            updatePanel.adresComboz.addItem(adresy.get(i).getId_a());
        }
        
        for(int i=0; i<klienci.size(); i++)
        {updatePanel.klientCombo.addItem(klienci.get(i).getId_k());
        updatePanel.klientCombo1.addItem(klienci.get(i).getId_k());
        }
        for(int i=0; i<zlecenia.size(); i++){
            updatePanel.zlecenieCombo.addItem(zlecenia.get(i).getId_z());
            
        }
        
        adresy.clear();
        pracownicy.clear();
        klienci.clear();
        zlecenia.clear();
       
        RightPanel.removeAll();
        RightPanel.repaint();
        RightPanel.revalidate();

        RightPanel.add(updatePanel);
        RightPanel.repaint();
        RightPanel.revalidate(); 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla jMenuItem2 - wykonuje metode obsługi zdarzeń dla jButton1
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
/**
     * Metoda obsługi zdarzenia dla jMenuItem3 - wykonuje metode obsługi zdarzeń dla dodajdobazyButton
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       dodajdobazyButtonActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla jMenuItem5 - wykonuje metode obsługi zdarzeń dla jButton4
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       jButton4ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla jMenuItem6 - wykonuje metode obsługi zdarzeń dla czyscbazeButton
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        czyscbazeButtonActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla jMenuItem7 - wykonuje metode obsługi zdarzeń dla jButton3
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jButton3ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla jMenuItem8 - wykonuje metode obsługi zdarzeń dla jButton2
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jButton2ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JToggleButton PolaczButton;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton czyscbazeButton;
    private projektpo.DodajPanel dodajPanel;
    private javax.swing.JButton dodajdobazyButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private projektpo.Panel1 panel11;
    private projektpo.ParsujPanel parsujPanel;
    private projektpo.UpdatePanel updatePanel;
    private projektpo.UsuwaniePanel usuwaniePanel;
    public static projektpo.WyswietlFrame wyswietlFrame;
    // End of variables declaration//GEN-END:variables
}
