/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektpo;
import baza.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.stream.XMLStreamException;
/**
 *Klasa dla jednego z paneli wyświetlanych w klasie Gui
 * @author Michał Rembisz
 */
public class ParsujPanel extends javax.swing.JPanel {
    private boolean dodajdolisty=false;
    private boolean dodajdobazy=false;
    /**
     * Creates new form parsujPanel
     */
    public ParsujPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bazaCheckBox = new javax.swing.JCheckBox();
        listaCheckBox = new javax.swing.JCheckBox();
        parsujButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        parsujArea = new javax.swing.JTextArea();

        bazaCheckBox.setText("Dodaj do bazy danych");

        listaCheckBox.setText("Dodaj do listy");

        parsujButton.setText("Parsuj z XML");
        parsujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parsujButtonActionPerformed(evt);
            }
        });

        parsujArea.setColumns(20);
        parsujArea.setRows(5);
        jScrollPane1.setViewportView(parsujArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bazaCheckBox)
                            .addComponent(listaCheckBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(parsujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(parsujButton, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(listaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bazaCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
/**
     * Metoda obsługi zdarzenia dla parsujButton - pobiera wartości zmiennych na podstawie checkboxów wykonuje metode parsowanieXML dane wypisuje w jTextArea1
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void parsujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parsujButtonActionPerformed
       if(listaCheckBox.isSelected()==true)
        dodajdolisty=true;
        if(bazaCheckBox.isSelected()==true)
        {
        dodajdolisty=true;
        dodajdobazy=true;
        }

        File xmlFile = new File("./dane/dane.xml");
        try {
            Parser.parsowanieXML(xmlFile,dodajdolisty,dodajdobazy);

        } catch (FileNotFoundException | XMLStreamException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(dodajdolisty==true)
        {
            String wynik="";
            System.out.println("Lista pars: ");
            wynik+="Pracownicy: \n";
            for(Pracownik q: Parser.zparsp)
            wynik+=q+"\n";
            
             wynik+="Klienci: \n";
            for(Klient q: Parser.zparsk)
             wynik+=q+"\n";
            wynik+="Adresy: \n";
            for(Adres q: Parser.zparsa)
             wynik+=q+"\n";
            wynik+="Zlecenia: \n";
            for(Zlecenie q: Parser.zparsz)
             wynik+=q+"\n";
            parsujArea.setText(wynik);
        }
        Gui.wyswietlFrame.clearAdresy();
        Gui.wyswietlFrame.clearKlienci();
        Gui.wyswietlFrame.clearPracownicy();
        Gui.wyswietlFrame.clearZlecenia();
        if(Gui.wyswietlFrame.isVisible()==true)
             Gui.wyswietlFrame.setVisible(false);
        
        Parser.zparsp.clear();
            Parser.zparsk.clear();
            Parser.zparsa.clear();
            Parser.zparsz.clear();
    }//GEN-LAST:event_parsujButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bazaCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox listaCheckBox;
    private javax.swing.JTextArea parsujArea;
    private javax.swing.JButton parsujButton;
    // End of variables declaration//GEN-END:variables
}
