/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektpo;

import baza.Adres;
import baza.Klient;
import baza.Pracownik;
import baza.Zlecenie;
import java.text.ParseException;
import java.util.List;
import javax.swing.text.MaskFormatter;
import static projektpo.Gui.b;

/**
 *Klasa dla jednego z paneli wyświetlanych w klasie Gui
 * @author Michał Rembisz
 */
public class UpdatePanel extends javax.swing.JPanel  {

    /**
     * Creates new form UpdatePanel
     */
    public UpdatePanel() {
        initComponents();
    }
    
    /**
     * Metoda sprawdza czy podany napis zawiera tylko cyfry i ma 9 znaków
     * @param tel zmienna typu String zawierająca napis do sprawdzenia
     * @return metoda zwraca wartość logiczną true lub false informującą czy podany napis zawiera tylko cyfry
     */
public  boolean checkTelefon(String tel){
         
        boolean SameLiczby=true;
        int i=0;
        while(SameLiczby==true && i<tel.length()){
            if(tel.charAt(i)<='0'|| tel.charAt(i)>='9'||tel.length()!=9){
                SameLiczby=false; 
            }
            ++i;
        } 
        return SameLiczby;
    }

    /**
     * Metoda sprawdza czy podany napis zawiera tylko cyfry
     * @param liczba zmienna typu String zawierająca napis do sprawdzenia
     * @return metoda zwraca wartość logiczną true lub false informującą czy podany napis zawiera tylko cyfry
     */
    public boolean checkLiczby (String liczba){
        boolean SameLiczby=true;
        int i=0;
        while(SameLiczby==true && i<liczba.length()){
            if(liczba.charAt(i)<='0'|| liczba.charAt(i)>='9'){
                SameLiczby=false; 
            }
            ++i;
        } 
        return SameLiczby;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        updatepButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uidpCombop = new javax.swing.JComboBox<>();
        uidaCombop = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uimiepField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        unazwiskopField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        urejonField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        uzmianaField = new javax.swing.JTextField();
        utel_ppField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        powiadoLabelup = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        podajPoczte = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        try
        {
            MaskFormatter kodpocztowy = new MaskFormatter("##-###");
            kodpocztowy.setValidCharacters("0123456789");
            kodField = new javax.swing.JFormattedTextField(kodpocztowy);
            podajnr_domu = new javax.swing.JTextField();
            jLabel9 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            podajUlice = new javax.swing.JTextField();
            podajMiejscowosc = new javax.swing.JTextField();
            jLabel12 = new javax.swing.JLabel();
            jLabel13 = new javax.swing.JLabel();
            adresCombo = new javax.swing.JComboBox<>();
            updatepButton1 = new javax.swing.JButton();
            powiadoLabelaa = new javax.swing.JLabel();
            jPanel3 = new javax.swing.JPanel();
            adresComboK = new javax.swing.JComboBox<>();
            podajTelefonK = new javax.swing.JTextField();
            podajNazwiskoK = new javax.swing.JTextField();
            podajImieK = new javax.swing.JTextField();
            jLabel14 = new javax.swing.JLabel();
            jLabel15 = new javax.swing.JLabel();
            jLabel16 = new javax.swing.JLabel();
            jLabel17 = new javax.swing.JLabel();
            klientCombo = new javax.swing.JComboBox<>();
            jLabel18 = new javax.swing.JLabel();
            updatepButton2 = new javax.swing.JButton();
            powiadoLabelak = new javax.swing.JLabel();
            jPanel4 = new javax.swing.JPanel();
            jLabel19 = new javax.swing.JLabel();
            typ_zlCombo = new javax.swing.JComboBox<>();
            adresComboz = new javax.swing.JComboBox<>();
            jLabel20 = new javax.swing.JLabel();
            jLabel21 = new javax.swing.JLabel();
            pracownikCombo = new javax.swing.JComboBox<>();
            klientCombo1 = new javax.swing.JComboBox<>();
            jLabel22 = new javax.swing.JLabel();
            zlecenieCombo = new javax.swing.JComboBox<>();
            jLabel23 = new javax.swing.JLabel();
            updatepButton3 = new javax.swing.JButton();
            powiadoLabelaz = new javax.swing.JLabel();

            updatepButton.setText("Aktualizuj dane");
            updatepButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    updatepButtonActionPerformed(evt);
                }
            });

            jLabel1.setText("Id_p:");

            uidpCombop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));
            uidpCombop.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    uidpCombopFocusLost(evt);
                }
            });

            uidaCombop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

            jLabel2.setText("Adres:");

            jLabel3.setText("Imie:");

            jLabel4.setText("Nazwisko:");

            jLabel5.setText("Rejon:");

            jLabel6.setText("Zmiana:");

            jLabel7.setText("Telefon:");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(powiadoLabelup))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(153, 153, 153)
                                    .addComponent(updatepButton)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(uidpCombop, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(uimiepField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                    .addComponent(unazwiskopField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(uzmianaField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(urejonField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(utel_ppField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(uidaCombop, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(uidpCombop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(uimiepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(unazwiskopField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(urejonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uzmianaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(utel_ppField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uidaCombop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(9, 9, 9)
                    .addComponent(powiadoLabelup)
                    .addGap(18, 18, 18)
                    .addComponent(updatepButton)
                    .addContainerGap(24, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Pracownik", jPanel1);

            jLabel11.setText("Poczta:");

            jLabel10.setText("Kod:");

        }
        catch (ParseException e) {
        }

        jLabel9.setText("Nr domu/mieszkania:");

        jLabel8.setText("Ulica:");

        jLabel12.setText("Miejscowość:");

        jLabel13.setText("Id_a:");

        adresCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));
        adresCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adresComboFocusLost(evt);
            }
        });

        updatepButton1.setText("Aktualizuj dane");
        updatepButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(podajUlice, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(podajMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(podajnr_domu, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(podajPoczte, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kodField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(adresCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(updatepButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(powiadoLabelaa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(adresCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(podajMiejscowosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(podajUlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(podajnr_domu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(kodField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(podajPoczte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powiadoLabelaa)
                .addGap(9, 9, 9)
                .addComponent(updatepButton1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adres", jPanel2);

        adresComboK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        jLabel14.setText("Imie:");

        jLabel15.setText("Nazwisko:");

        jLabel16.setText("Telefon:");

        jLabel17.setText("Adres:");

        klientCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));
        klientCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                klientComboFocusLost(evt);
            }
        });

        jLabel18.setText("Id_k:");

        updatepButton2.setText("Aktualizuj dane");
        updatepButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(podajTelefonK)
                            .addComponent(adresComboK, 0, 299, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(powiadoLabelak)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14)
                                .addComponent(jLabel18)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(klientCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(podajNazwiskoK)
                            .addComponent(podajImieK))))
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(updatepButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(klientCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(podajImieK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(podajNazwiskoK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(podajTelefonK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(adresComboK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(powiadoLabelak)
                .addGap(11, 11, 11)
                .addComponent(updatepButton2)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Klient", jPanel3);

        jLabel19.setText("Typ zlecenia:");

        typ_zlCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz", "Naprawa", "Instalacja", "Deinstalacja", "Wycena" }));

        adresComboz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        jLabel20.setText("Adres:");

        jLabel21.setText("Pracownik:");

        pracownikCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        klientCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        jLabel22.setText("Klient:");

        zlecenieCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));
        zlecenieCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                zlecenieComboFocusLost(evt);
            }
        });

        jLabel23.setText("Id_z:");

        updatepButton3.setText("Aktualizuj dane");
        updatepButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(klientCombo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pracownikCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typ_zlCombo, 0, 324, Short.MAX_VALUE)
                    .addComponent(adresComboz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zlecenieCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(updatepButton3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(powiadoLabelaz)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zlecenieCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(typ_zlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresComboz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pracownikCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(klientCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powiadoLabelaz)
                .addGap(8, 8, 8)
                .addComponent(updatepButton3)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Zlecenie", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Metoda obsługi zdarzenia dla uidpCombop - w sytuacji gdy użytkownik wybierze wartość z uidpCombop i kliknie w inne pole metoda wyświetli wartości odpowidnich pól dla obiektu Klasy Pracownik
     * o podanym id
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void uidpCombopFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uidpCombopFocusLost
      
        List<Pracownik> pracownicy = b.selectPracownicy();
      
        
        if(uidpCombop.getSelectedItem().toString()=="Wybierz")
        {
            powiadoLabelup.setText("Wybierz rekord do aktualizacji");
        }
        else
        {
            String id_p=uidpCombop.getSelectedItem().toString();
            int id=Integer.parseInt(id_p);
            id=id-1;
            String imie=pracownicy.get(id).getImie();
            uimiepField.setText(imie);
            String nazwisko=pracownicy.get(id).getNazwisko();
            unazwiskopField.setText(nazwisko);
            String rejon=pracownicy.get(id).getRejon();
            urejonField.setText(rejon);
            String zmiana=pracownicy.get(id).getZmiana();
            uzmianaField.setText(zmiana);
            String tel_p=pracownicy.get(id).getTel_p();
            utel_ppField.setText(tel_p);
            String id_a=pracownicy.get(id).getId_a();
            uidaCombop.setSelectedItem(id_a);
        }
        
        
        pracownicy.clear();
       
    }//GEN-LAST:event_uidpCombopFocusLost

    /**
     * Metoda obsługi zdarzenia dla updatepButton - pobiera wartości zmiennych z pól tekstowych, sprawdza czy wszystkie pola są prawidłowo wypełnione
     * oraz aktualizuje rekord z bazy danych z tabeli pracownicy i aktualizuje wiersz z obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void updatepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepButtonActionPerformed
        
        
        
        
        boolean dodaj=true;
        String tel_p="0";
        if(checkTelefon(utel_ppField.getText())==true){
            tel_p=utel_ppField.getText();
            
        }else{
            dodaj=false;
            powiadoLabelup.setText("Nie poprawny numer telefonu");   
        }
                      
        String imie =uimiepField.getText();
        String nazwisko=unazwiskopField.getText();
        String rejon=urejonField.getText();        
        String zmiana=uzmianaField.getText(); 
        
        if(uimiepField.getText().equals("")||unazwiskopField.getText().equals("")||urejonField.getText().equals("")||uzmianaField.getText().equals("")||
                                    utel_ppField.getText().equals("")||uidaCombop.getSelectedItem().equals("Wybierz")||uidpCombop.getSelectedItem().equals("Wybierz")){
            powiadoLabelup.setText("Nie wprowadzono wszystkich danych");
            dodaj=false;
        }
        Object id_a=uidaCombop.getSelectedItem();
        Object id_p=uidpCombop.getSelectedItem();
        
        if(dodaj==true){
            
            
           int key=Gui.wyswietlFrame.getRowPracownicy(uidpCombop.getSelectedItem().toString());
            
             Gui.wyswietlFrame.updateRowsPracownicy(key,id_p.toString(),imie,nazwisko,rejon,zmiana,tel_p,id_a.toString());
             powiadoLabelup.setText("");
             
      
        }
        
    }//GEN-LAST:event_updatepButtonActionPerformed

    /**
     * Metoda obsługi zdarzenia dla updatepButton1 - pobiera wartości zmiennych z pól tekstowych, sprawdza czy wszystkie pola są prawidłowo wypełnione
     * oraz aktualizuje rekord z bazy danych z tabeli adresy i aktualizuje wiersz z obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void updatepButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepButton1ActionPerformed
        boolean dodaj=true;
        String miejscowosc =podajMiejscowosc.getText();
        String ulica=podajUlice.getText();
        String nr_domu=podajnr_domu.getText();        
        String kod=kodField.getText(); 
        String poczta=podajPoczte.getText(); 
        
        if(podajMiejscowosc.getText().equals("")||podajUlice.getText().equals("")||podajnr_domu.getText().equals("")||kodField.getText().equals("  -   ")||
                                    podajPoczte.getText().equals("")){
            powiadoLabelaa.setText("Nie wprowadzono wszystkich danych");
            dodaj=false;
        }
        Object id_a = adresCombo.getSelectedItem();
         if(dodaj==true){
            
            
           int key=Gui.wyswietlFrame.getRowAdresy(adresCombo.getSelectedItem().toString());
            
             Gui.wyswietlFrame.updateRowsAdresy(key,id_a.toString(),miejscowosc,ulica,nr_domu,kod,poczta);
             powiadoLabelup.setText("");
             
      
        }
    }//GEN-LAST:event_updatepButton1ActionPerformed

     /**
     * Metoda obsługi zdarzenia dla adresCombo - w sytuacji gdy użytkownik wybierze wartość z adresCombo i kliknie w inne pole metoda wyświetli wartości odpowidnich pól dla obiektu klasy Adres
     * o podanym id
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void adresComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adresComboFocusLost
       List<Adres> adresy = b.selectAdresy();
      
        
        if(adresCombo.getSelectedItem().toString()=="Wybierz")
        {
            powiadoLabelaa.setText("Wybierz rekord do aktualizacji");
            
        }
        else
        {
            String id_p=adresCombo.getSelectedItem().toString();
            int id=Integer.parseInt(id_p);
            id=id-1;
            String imie=adresy.get(id).getMiejscowosc();
            podajMiejscowosc.setText(imie);
            String nazwisko=adresy.get(id).getUlica();
            podajUlice.setText(nazwisko);
            String rejon=adresy.get(id).getNr_domu();
            podajnr_domu.setText(rejon);
            String zmiana=adresy.get(id).getKod();
            kodField.setText(zmiana);
            String poczta=adresy.get(id).getPoczta();
            podajPoczte.setText(poczta);
            
        }
        
        
        adresy.clear();
       
    }//GEN-LAST:event_adresComboFocusLost

    /**
     * Metoda obsługi zdarzenia dla updatepButton2 - pobiera wartości zmiennych z pól tekstowych, sprawdza czy wszystkie pola są prawidłowo wypełnione
     * oraz aktualizuje rekord z bazy danych z tabeli klienci i aktualizuje wiersz z obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void updatepButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepButton2ActionPerformed
         
        List<Klient> klienci = Gui.b.selectKlienci();
        boolean dodaj=true;
        String tel_k="0";
        if(checkTelefon(podajTelefonK.getText())==true){
            tel_k=podajTelefonK.getText();
            
        }else{
            dodaj=false;
            powiadoLabelak.setText("Nie poprawny numer telefonu");   
        }
        
        String imie =podajImieK.getText();
        String nazwisko=podajNazwiskoK.getText();
        
        
        if(podajImieK.getText().equals("")||podajNazwiskoK.getText().equals("")||
                                    podajTelefonK.getText().equals("")||adresComboK.getSelectedItem().equals("")){
            powiadoLabelak.setText("Nie wprowadzono wszystkich danych");
            dodaj=false;
        }
        Object id_a=adresComboK.getSelectedItem();
        Object id_k=klientCombo.getSelectedItem();
        if(dodaj==true){
            
            
           int key=Gui.wyswietlFrame.getRowKlienci(klientCombo.getSelectedItem().toString());
            
             Gui.wyswietlFrame.updateRowsKlienci(key,id_k.toString(),imie,nazwisko,tel_k,id_a.toString());
             powiadoLabelak.setText("");
             
      
        }
        
    }//GEN-LAST:event_updatepButton2ActionPerformed

     /**
     * Metoda obsługi zdarzenia dla klientCombo - w sytuacji gdy użytkownik wybierze wartość z klientCombo i kliknie w inne pole metoda wyświetli wartości odpowidnich pól dla obiektu klasy Klient
     * o podanym id
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void klientComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_klientComboFocusLost
         List<Klient> klienci = b.selectKlienci();
      
        
        if(klientCombo.getSelectedItem().toString()=="Wybierz")
        {
            powiadoLabelak.setText("Wybierz rekord do aktualizacji");
        }
        else
        {
            String id_k=klientCombo.getSelectedItem().toString();
            int id=Integer.parseInt(id_k);
            id=id-1;
            String imie=klienci.get(id).getImie();
            podajImieK.setText(imie);
            String nazwisko=klienci.get(id).getNazwisko();
            podajNazwiskoK.setText(nazwisko);
            String rejon=klienci.get(id).getTel_k();
            podajTelefonK.setText(rejon);
            String id_a=klienci.get(id).getId_a();
            adresComboK.setSelectedItem(id_a);
            
        }
        
        
        klienci.clear();
    }//GEN-LAST:event_klientComboFocusLost

    /**
     * Metoda obsługi zdarzenia dla updatepButton3 - pobiera wartości zmiennych z pól tekstowych, sprawdza czy wszystkie pola są prawidłowo wypełnione
     * oraz aktualizuje rekord z bazy danych z tabeli zlecenia i aktualizuje wiersz z obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void updatepButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepButton3ActionPerformed
        List<Zlecenie> zlecenia = Gui.b.selectZlecenia();
        boolean dodaj=true;
        String tel_k="0";
        
        
        
        
        if(adresComboz.getSelectedItem().equals("Wybierz")||klientCombo1.getSelectedItem().equals("Wybierz")||pracownikCombo.getSelectedItem().equals("Wybierz")
                ||zlecenieCombo.getSelectedItem().equals("Wybierz")||typ_zlCombo.getSelectedItem().equals("Wybierz")){
            powiadoLabelak.setText("Nie wprowadzono wszystkich danych");
            dodaj=false;
        }
        Object id_a=adresComboz.getSelectedItem();
        Object id_k=klientCombo1.getSelectedItem();
        Object id_p=pracownikCombo.getSelectedItem();
        Object id_z=zlecenieCombo.getSelectedItem();
        Object typ=typ_zlCombo.getSelectedItem();
        if(dodaj==true){
            
            
           int key=Gui.wyswietlFrame.getRowZlecenia(zlecenieCombo.getSelectedItem().toString());
            
             Gui.wyswietlFrame.updateRowsZlecenia(key,id_z.toString(),typ.toString(),id_a.toString(),id_p.toString(),id_k.toString());
             powiadoLabelak.setText("");
             
      
        }
    }//GEN-LAST:event_updatepButton3ActionPerformed

    /**
     * Metoda obsługi zdarzenia dla zlecenieCombo - w sytuacji gdy użytkownik wybierze wartość z zlecenieCombo i kliknie w inne pole metoda wyświetli wartości odpowidnich pól dla obiektu 
     * klasy Zlecenie o podanym id
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void zlecenieComboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zlecenieComboFocusLost
        List<Zlecenie> zlecenia = b.selectZlecenia();
      
        
        if(zlecenieCombo.getSelectedItem().toString()=="Wybierz")
        {
            powiadoLabelaz.setText("Wybierz rekord do aktualizacji");
        }
        else
        {
            String id_z=zlecenieCombo.getSelectedItem().toString();
            int id=Integer.parseInt(id_z);
            id=id-1;
            String typ=zlecenia.get(id).getTyp_zl();
            typ_zlCombo.setSelectedItem(typ);
            String id_a=zlecenia.get(id).getId_a();
            adresComboz.setSelectedItem(id_a);
            String id_p=zlecenia.get(id).getId_p();
            pracownikCombo.setSelectedItem(id_p);
            String id_k=zlecenia.get(id).getId_k();
            klientCombo1.setSelectedItem(id_k);
            
            
        }
        
        
        zlecenia.clear();
    }//GEN-LAST:event_zlecenieComboFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> adresCombo;
    public javax.swing.JComboBox<String> adresComboK;
    public javax.swing.JComboBox<String> adresComboz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JComboBox<String> klientCombo;
    public javax.swing.JComboBox<String> klientCombo1;
    private javax.swing.JFormattedTextField kodField;
    private javax.swing.JTextField podajImieK;
    private javax.swing.JTextField podajMiejscowosc;
    private javax.swing.JTextField podajNazwiskoK;
    private javax.swing.JTextField podajPoczte;
    private javax.swing.JTextField podajTelefonK;
    private javax.swing.JTextField podajUlice;
    private javax.swing.JTextField podajnr_domu;
    private javax.swing.JLabel powiadoLabelaa;
    private javax.swing.JLabel powiadoLabelak;
    private javax.swing.JLabel powiadoLabelaz;
    private javax.swing.JLabel powiadoLabelup;
    public javax.swing.JComboBox<String> pracownikCombo;
    private javax.swing.JComboBox<String> typ_zlCombo;
    public javax.swing.JComboBox<String> uidaCombop;
    public javax.swing.JComboBox<String> uidpCombop;
    private javax.swing.JTextField uimiepField;
    private javax.swing.JTextField unazwiskopField;
    private javax.swing.JButton updatepButton;
    private javax.swing.JButton updatepButton1;
    private javax.swing.JButton updatepButton2;
    private javax.swing.JButton updatepButton3;
    private javax.swing.JTextField urejonField;
    private javax.swing.JTextField utel_ppField;
    private javax.swing.JTextField uzmianaField;
    public javax.swing.JComboBox<String> zlecenieCombo;
    // End of variables declaration//GEN-END:variables
}
