/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektpo;

import baza.Adres;
import baza.Klient;
import baza.Pracownik;
import java.util.List;

/**
 *Klasa dla jednego z paneli wyświetlanych w klasie Gui
 * @author Michał Rembisz
 */
public class UsuwaniePanel extends javax.swing.JPanel {

    /**
     * Creates new form usuwaniePanel
     */
    public UsuwaniePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        utCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uidpCombo = new javax.swing.JComboBox<>();
        powiadoLabelup = new javax.swing.JLabel();
        usunpButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        uidaCombo = new javax.swing.JComboBox<>();
        usunaButton = new javax.swing.JButton();
        powiadoLabelua = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        usunkButton = new javax.swing.JButton();
        uidkCombo = new javax.swing.JComboBox<>();
        utkCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        powiadoLabeluk = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        uidzCombo = new javax.swing.JComboBox<>();
        usunzButton = new javax.swing.JButton();
        powiadoLabeluz = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Podaj numer telefonu pracownika do usunięcia lub jego aktualne id");

        utCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        jLabel2.setText("Numer telefonu:");

        jLabel3.setText("Id_p:");

        uidpCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        usunpButton.setText("Usuń");
        usunpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(utCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(uidpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(powiadoLabelup)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(usunpButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(utCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uidpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(powiadoLabelup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usunpButton)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pracownik", jPanel1);

        jLabel4.setText("Id_a:");

        uidaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        usunaButton.setText("Usuń");
        usunaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunaButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Podaj aktualne id adresu do usunięcia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(361, 361, 361))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(usunaButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(powiadoLabelua))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uidaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uidaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powiadoLabelua)
                .addGap(25, 25, 25)
                .addComponent(usunaButton)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adresy", jPanel2);

        usunkButton.setText("Usuń");
        usunkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunkButtonActionPerformed(evt);
            }
        });

        uidkCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        utkCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        jLabel6.setText("Numer telefonu:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Podaj numer telefonu klienta do usunięcia lub jego aktualne id");

        jLabel8.setText("id_k:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(utkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(uidkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(powiadoLabeluk))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(usunkButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(utkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uidkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(powiadoLabeluk)
                .addGap(24, 24, 24)
                .addComponent(usunkButton)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Klienci", jPanel3);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Podaj aktualne id zlecenia do usunięcia");

        jLabel10.setText("Id_z:");

        uidzCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz" }));

        usunzButton.setText("Usuń");
        usunzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunzButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(351, 351, 351))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(usunzButton))
                        .addComponent(uidzCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(jLabel9)))
                    .addComponent(powiadoLabeluz))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uidzCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(powiadoLabeluz)
                .addGap(31, 31, 31)
                .addComponent(usunzButton)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Zlecenia", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda obsługi zdarzenia dla usunpButton - pobiera wartości zmiennych z jComboBoxów, sprawdza czy wszystkie pola są wybrane
     * oraz usuwa rekord z bazy danych z tabeli pracownicy i usuwa wiersz z obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void usunpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunpButtonActionPerformed
       
        boolean usun=false;
        String co="";
        
        
        if(utCombo.getSelectedItem().toString()=="Wybierz"&&uidpCombo.getSelectedItem().toString()=="Wybierz")
        {
            powiadoLabelup.setText("Wybierz jedno z pól");
        }
        else if(uidpCombo.getSelectedItem().toString()=="Wybierz")
        {
            co="tel_p=";
            co+=utCombo.getSelectedItem().toString();
            
            try{
        
       
         Gui.b.wykonajZapytanie("DELETE from pracownicy WHERE "+co+";");
       usun=true;
            } catch ( Exception e ) {
             System.err.println( e.getClass().getName() + ": " + e.getMessage() );
          
            }
            System.out.println("Usunięto rekord");
            if(usun==true)
            {
            int key=Gui.wyswietlFrame.getRowPracownicy(utCombo.getSelectedItem().toString()); 
            Gui.wyswietlFrame.removeRowPracownicy(key);
            }
        }
        else if(utCombo.getSelectedItem().toString()=="Wybierz")
        {
            co="id_p=";
            co+=uidpCombo.getSelectedItem().toString();
            try{
        
       
        Gui.b.wykonajZapytanie("DELETE from pracownicy WHERE "+co+";");
        usun=true;
       
        } catch ( Exception e ) {
          System.err.println( e.getClass().getName() + ": " + e.getMessage() );
          
        }
        System.out.println("Usunięto rekord");
        }
        
        
        
        
        if(usun==true)
            {
            int key=Gui.wyswietlFrame.getRowPracownicy(uidpCombo.getSelectedItem().toString()); 
            Gui.wyswietlFrame.removeRowPracownicy(key);
            powiadoLabelua.setText("");
            }
       
       
    }//GEN-LAST:event_usunpButtonActionPerformed

    /**
     * Metoda obsługi zdarzenia dla usunaButton - pobiera wartości zmiennych z jComboBoxów, sprawdza czy wszystkie pola są wybrane
     * oraz usuwa rekord z bazy danych z tabeli adresy i usuwa wiersz z obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void usunaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunaButtonActionPerformed
         List<Klient> klienci = Gui.b.selectKlienci();
          List<Pracownik> pracownicy = Gui.b.selectPracownicy();
         
        boolean usun=false;
        String co="";
        
        if(uidaCombo.getSelectedItem().toString()=="Wybierz")
        {
            powiadoLabelua.setText("Wybierz jedno z pól");
        }
        else{
        
            co="id_a=";
            co+=uidaCombo.getSelectedItem().toString();
            
            try{
        
       
         Gui.b.wykonajZapytanie("DELETE from adresy WHERE "+co+";");
       usun=true;
            } catch ( Exception e ) {
             System.err.println( e.getClass().getName() + ": " + e.getMessage() );
          
            }
            
            
        }
        
        for(int i=0;i<pracownicy.size();i++){
            if(pracownicy.get(i).getId_a().equals(uidaCombo.getSelectedItem())){
                usun=false;
                powiadoLabelua.setText("Nie można usunąć tego adresu ponieważ ktoś mieszka pod tym adresem");
            }
        }
        
        for(int i=0;i<klienci.size();i++){
            if(klienci.get(i).getId_a().equals(uidaCombo.getSelectedItem())){
                usun=false;
                powiadoLabelua.setText("Nie można usunąć tego adresu ponieważ ktoś mieszka pod tym adresem");
            }
        }
        
        if(usun==true)
            {
            int key=Gui.wyswietlFrame.getRowAdresy(uidaCombo.getSelectedItem().toString()); 
            Gui.wyswietlFrame.removeRowAdresy(key);
            powiadoLabelua.setText("");
            }
        
    }//GEN-LAST:event_usunaButtonActionPerformed

    /**
     * Metoda obsługi zdarzenia dla usunkButton - pobiera wartości zmiennych z jComboBoxów, sprawdza czy wszystkie pola są wybrane
     * oraz usuwa rekord z bazy danych z tabeli klienci i usuwa wiersz z obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void usunkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunkButtonActionPerformed
        boolean usun=false;
        String co="";
        
        
        if(utkCombo.getSelectedItem().toString()=="Wybierz"&&uidkCombo.getSelectedItem().toString()=="Wybierz"||utkCombo.getSelectedItem().toString()!="Wybierz"&&uidkCombo.getSelectedItem().toString()!="Wybierz")
        {
            powiadoLabeluk.setText("Wybierz jedno z pól");
        }
        else if(uidkCombo.getSelectedItem().toString()=="Wybierz")
        {
            co="tel_k=";
            co+=utkCombo.getSelectedItem().toString();
            
            try{
        
       
         Gui.b.wykonajZapytanie("DELETE from klienci WHERE "+co+";");
       usun=true;
            } catch ( Exception e ) {
             System.err.println( e.getClass().getName() + ": " + e.getMessage() );
          
            }
            System.out.println("Usunięto rekord");
            if(usun==true)
            {
            int key=Gui.wyswietlFrame.getRowKlienci(utkCombo.getSelectedItem().toString()); 
            Gui.wyswietlFrame.removeRowKlienci(key);
            }
        }
        else if(utkCombo.getSelectedItem().toString()=="Wybierz")
        {
            co="id_k=";
            co+=uidkCombo.getSelectedItem().toString();
            try{
        
       
        Gui.b.wykonajZapytanie("DELETE from klienci WHERE "+co+";");
        usun=true;
       
        } catch ( Exception e ) {
          System.err.println( e.getClass().getName() + ": " + e.getMessage() );
          
        }
        System.out.println("Usunięto rekord");
        }
        
        
        
        
        if(usun==true)
            {
            int key=Gui.wyswietlFrame.getRowKlienci(uidkCombo.getSelectedItem().toString()); 
            Gui.wyswietlFrame.removeRowKlienci(key);
            powiadoLabelua.setText("");
            }
       
    }//GEN-LAST:event_usunkButtonActionPerformed

    /**
     * Metoda obsługi zdarzenia dla usunzButton - pobiera wartości zmiennych z jComboBoxów, sprawdza czy wszystkie pola są wybrane
     * oraz usuwa rekord z bazy danych z tabeli zlecenia i usuwa wiersz z obiektu jTable w klasie WyswietlFrame
     * @param evt pobiera informacje o wykonaniu zdarzenia
     */
    private void usunzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunzButtonActionPerformed

        boolean usun=false;
        String co="";
        
        if(uidzCombo.getSelectedItem().toString()=="Wybierz")
        {
            powiadoLabeluz.setText("Wybierz jedno z pól");
        }
        else{
        
            co="id_z=";
            co+=uidzCombo.getSelectedItem().toString();
            
            try{
        
       
         Gui.b.wykonajZapytanie("DELETE from zlecenia WHERE "+co+";");
       usun=true;
            } catch ( Exception e ) {
             System.err.println( e.getClass().getName() + ": " + e.getMessage() );
          
            }
            
            
        }
         if(usun==true)
            {
            int key=Gui.wyswietlFrame.getRowZlecenia(uidzCombo.getSelectedItem().toString()); 
            Gui.wyswietlFrame.removeRowZlecenia(key);
            powiadoLabelua.setText("");
            }
    }//GEN-LAST:event_usunzButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel powiadoLabelua;
    private javax.swing.JLabel powiadoLabeluk;
    private javax.swing.JLabel powiadoLabelup;
    private javax.swing.JLabel powiadoLabeluz;
    public javax.swing.JComboBox<String> uidaCombo;
    public javax.swing.JComboBox<String> uidkCombo;
    public javax.swing.JComboBox<String> uidpCombo;
    public javax.swing.JComboBox<String> uidzCombo;
    private javax.swing.JButton usunaButton;
    private javax.swing.JButton usunkButton;
    private javax.swing.JButton usunpButton;
    private javax.swing.JButton usunzButton;
    public javax.swing.JComboBox<String> utCombo;
    public javax.swing.JComboBox<String> utkCombo;
    // End of variables declaration//GEN-END:variables
}
